# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ mrp ]
  pull_request:
    branches: [ mrp ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
        framework: ['ucca', 'amr', 'dm', 'eds', 'psd', 'output']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest cython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v tests
    - name: Test
      run: |
        python -m tupa -t test_files/${{ matrix.framework }}.mrp -d test_files/${{ matrix.framework }}.mrp -m ${{ matrix.framework }} --conllu test_files/udpipe.mrp --alignment test_files/isi.mrp -I2 --max-edge-labels=10 --max-node-labels=10 --max-node-properties=10 --max-words=10 --max-lemmas=10 --lstm-layer-dim=10 --timeout=1 -v
        python -m tupa test_files/input.mrp -m ${{ matrix.framework }} --conllu test_files/udpipe.mrp --alignment test_files/isi.mrp --timeout=1 -v
